/**
 * Shared SEO metadata — imported by both App.jsx (client) and
 * scripts/prerender-seo.mjs (build-time).
 * Keep this file free of DOM, React, and browser-only APIs.
 */

export const BASE_URL = 'https://fileconverter-three.vercel.app';

/** Routes that must be noindex */
export const NOINDEX_ROUTES = new Set(['/analytics']);

/** Per-route meta descriptions (150–160 chars target) */
export const PAGE_META = {
  '/': 'PixConvert: free online PDF & image converter. Merge, split, compress, convert, rotate, watermark, and protect your files right in your browser. No sign-up, no uploads, 100% private.',
  '/tools': 'Browse 40+ free PDF and image tools on PixConvert. Merge, split, compress, convert, rotate, and more — all running entirely in your browser. No account or upload needed.',
  '/about': 'Learn why PixConvert is 100% client-side and privacy-first. No accounts, no server uploads, no tracking — your files never leave your device. Here\'s how it all works.',
  '/privacy': 'PixConvert Privacy Policy: your files never leave your browser. Zero data collection, zero tracking, zero server uploads — ever. Read our full commitment to your privacy.',
  '/contact': 'Have a question or found a bug? Contact the PixConvert team and we\'ll respond within 24 hours. Feedback, feature requests, and bug reports are all welcome anytime.',
  '/api': 'PixConvert REST API docs — integrate PDF and image conversion into your apps. Full endpoint reference with curl examples, authentication guide, and request/response details.',
  '/analytics': 'PixConvert usage analytics — real-time metrics on tool usage.',
  '/tools/converter': 'Convert images between PNG, JPEG, WebP, AVIF, BMP, TIFF, HEIC and more — free, instant, 100% in your browser. No upload required, no account needed, completely private.',
  '/tools/gif': 'Create animated GIFs from images or video frames — free online GIF maker in your browser. Set frame rate, size, and loop. No upload or account required.',
  '/tools/merge-pdf': 'Merge multiple PDFs into one document — free, instant, and private. Drag to reorder, then combine PDFs in seconds. No file upload to any server, no sign-up required.',
  '/tools/split-pdf': 'Split a PDF into separate pages or custom ranges — free, private, entirely in your browser. Extract the exact pages you need. No upload, no account required.',
  '/tools/pdf': 'Remove PDF password protection instantly — free online PDF unlocker. Unlock encrypted PDFs right in your browser. No file upload to any server, 100% private.',
  '/tools/pdf-lock': 'Add password protection to any PDF — free online PDF locker. Set owner and user passwords to secure your documents. 100% private, no upload, works in your browser.',
  '/tools/compress-pdf': 'Compress PDF file size without losing quality — free online PDF compressor. Reduce large PDFs for email or storage instantly. No file upload required, completely private.',
  '/tools/pdf-to-jpg': 'Convert PDF pages to high-quality JPG images — free, fast, no sign-up. Extract every page as a separate JPG or download all pages in a ZIP file instantly.',
  '/tools/pdf-to-word': 'Convert PDF to editable Word (DOCX) — free online PDF to Word converter. Preserve formatting and layout. No upload to any server, instant results in your browser.',
  '/tools/pdf-to-powerpoint': 'Convert PDF to editable PowerPoint (PPTX) — free online tool. Preserve slides and structure. No upload required, instant results in your browser, completely private.',
  '/tools/pdf-to-excel': 'Convert PDF to Excel spreadsheet (XLSX) — free PDF to Excel converter. Extract tables and data from PDFs instantly. No upload required, works in your browser.',
  '/tools/pdf-to-pdf-a': 'Convert PDF to PDF/A archival format — free online converter for long-term digital preservation. No upload to any server, no sign-up, instant results in your browser.',
  '/tools/remove-pages': 'Remove unwanted pages from any PDF — free online tool. Select pages to delete by number or range, then download the updated PDF instantly. No upload, no sign-up.',
  '/tools/extract-pages': 'Extract specific pages from any PDF — free online tool. Select any page range and save as a new PDF file instantly. No upload to any server, no sign-up required.',
  '/tools/organize-pdf': 'Reorder, rotate, and organize PDF pages — free online organizer. Drag and drop to rearrange any page however you need. No upload required, works entirely in your browser.',
  '/tools/scan-to-pdf': 'Convert scanned images and photos to a PDF — free scan to PDF tool. Combine multiple scans into one file. Works entirely in your browser, no upload or sign-up needed.',
  '/tools/jpg-to-pdf': 'Combine JPG images into a single PDF — free online JPG to PDF converter. Add multiple images, control their order and layout. No upload to any server, completely private.',
  '/tools/word-to-pdf': 'Convert Word documents (DOCX) to PDF — free online Word to PDF converter. Preserve formatting and layout precisely. No upload required, instant results, completely private.',
  '/tools/powerpoint-to-pdf': 'Convert PowerPoint presentations (PPTX) to PDF — free online tool. Preserve all slides, fonts, and formatting. No upload required, instant results, works in your browser.',
  '/tools/excel-to-pdf': 'Convert Excel spreadsheets (XLSX) to PDF — free Excel to PDF converter. Preserve tables and data in the output. No upload to any server, instant results.',
  '/tools/html-to-pdf': 'Convert HTML to PDF — free online HTML to PDF converter. Paste your HTML or enter a URL and get a perfectly rendered PDF instantly. No upload to any server required.',
  '/tools/rotate-pdf': 'Rotate PDF pages by 90°, 180°, or 270° — free online rotation tool. Rotate all pages or individual pages in any direction. No upload, works entirely in your browser.',
  '/tools/add-page-numbers': 'Add page numbers to any PDF — free online tool. Customize position, font size, and numbering format. No upload to any server, instant results, completely private.',
  '/tools/add-watermark': 'Add a text or image watermark to any PDF — free online tool. Customize opacity, position, and style. No upload required, works entirely in your browser.',
  '/tools/crop-pdf': 'Crop and trim PDF pages — free online PDF cropper. Remove margins, resize page dimensions, and adjust content layout. Works entirely in your browser, no upload required.',
  '/tools/edit-pdf': 'Edit PDF files online free — add text, images, shapes, and annotations. All editing runs entirely in your browser, nothing is uploaded to any server, instant results.',
  '/tools/jpg-to-png': 'Convert JPG to PNG free online — lossless, instant, no upload required. Preserve transparency and full image quality when converting JPEG photos to PNG format.',
  '/tools/png-to-jpg': 'Convert PNG to JPG free online — fast, easy, no upload required. Reduce file size by converting PNG images to compressed JPEG format. Completely private.',
  '/tools/webp-to-jpg': 'Convert WebP images to JPG free online — instant, no upload required. Download compatible JPEG files from any WebP image. Works in your browser, completely private.',
  '/tools/heic-to-jpg': 'Convert HEIC photos to JPG free online — no upload required. Open iPhone and iOS HEIC images on any device by converting them to universal JPEG format instantly.',
  '/tools/bmp-to-png': 'Convert BMP images to PNG free online — lossless conversion, no upload required. Reduce BMP file size significantly while preserving full image quality with PNG.',
  '/tools/photo-to-markdown': 'Extract text from photos using OCR and convert to Markdown — free, runs entirely in your browser, no upload required. Great for notes, docs, and content workflows.',
  '/tools/ocr-pdf': 'Extract text from scanned PDFs using OCR — free online PDF OCR tool. Make scanned documents searchable and copyable. Runs in your browser, no upload required.',
  '/tools/sign-pdf': 'Sign PDF files online free — draw, type, or upload your signature. 100% private, no upload to any server, runs entirely in your browser. Instant and easy to use.',
  '/tools/redact-pdf': 'Permanently redact sensitive text and images from PDFs — free online tool. Completely remove confidential information. No upload required, fully private and instant.',
  '/tools/compare-pdf': 'Compare two PDF files side-by-side and highlight differences — free online PDF diff tool. Spot changes instantly with visual highlighting. No upload required.',
};

/** Per-route page titles (50–60 chars target) */
export const PAGE_TITLES = {
  '/': 'PixConvert — Free Online PDF & Image Converter | 40+ Tools',
  '/tools': 'All PDF & Image Tools — Free, No Upload | PixConvert',
  '/about': 'About PixConvert — Free Browser-Based File Converter',
  '/privacy': 'PixConvert Privacy Policy — No Data, No Uploads',
  '/contact': 'Contact PixConvert — Free PDF & Image Converter Help',
  '/api': 'PixConvert API Docs — PDF & Image Conversion REST API',
  '/tools/converter': 'Free Image Converter Online — PNG, WebP, AVIF | PixConvert',
  '/tools/gif': 'Free GIF Maker Online — Create Animated GIFs | PixConvert',
  '/tools/pdf': 'Unlock PDF Online Free — Remove PDF Password | PixConvert',
  '/tools/pdf-lock': 'Protect PDF with Password Free Online | PixConvert',
  '/tools/pdf-to-jpg': 'Convert PDF to JPG Free Online — High Quality | PixConvert',
  '/tools/pdf-to-word': 'Convert PDF to Word (DOCX) Free Online | PixConvert',
  '/tools/pdf-to-powerpoint': 'Convert PDF to PowerPoint Free Online | PixConvert',
  '/tools/pdf-to-excel': 'Convert PDF to Excel (XLSX) Free Online | PixConvert',
  '/tools/pdf-to-pdf-a': 'Convert PDF to PDF/A Format Free Online | PixConvert',
  '/tools/merge-pdf': 'Merge PDF Files Free Online — No Upload | PixConvert',
  '/tools/split-pdf': 'Split PDF Online Free — Extract Pages Instantly | PixConvert',
  '/tools/remove-pages': 'Remove Pages from PDF Free Online — No Upload | PixConvert',
  '/tools/extract-pages': 'Extract PDF Pages Free Online — No Upload | PixConvert',
  '/tools/organize-pdf': 'Organize & Reorder PDF Pages Free Online | PixConvert',
  '/tools/scan-to-pdf': 'Scan to PDF Free — Camera & Image to PDF | PixConvert',
  '/tools/jpg-to-pdf': 'Convert JPG to PDF Free Online — No Upload | PixConvert',
  '/tools/word-to-pdf': 'Convert Word to PDF Free Online — DOCX to PDF | PixConvert',
  '/tools/powerpoint-to-pdf': 'Convert PowerPoint to PDF Free Online | PixConvert',
  '/tools/excel-to-pdf': 'Convert Excel to PDF Free Online — XLSX to PDF | PixConvert',
  '/tools/html-to-pdf': 'Convert HTML to PDF Free Online — No Upload | PixConvert',
  '/tools/rotate-pdf': 'Rotate PDF Pages Free Online — 90°, 180° | PixConvert',
  '/tools/add-page-numbers': 'Add Page Numbers to Any PDF Free Online | PixConvert',
  '/tools/add-watermark': 'Add Watermark to PDF Online Free — Text & Image | PixConvert',
  '/tools/crop-pdf': 'Crop PDF Pages Free Online — Trim & Resize | PixConvert',
  '/tools/edit-pdf': 'Edit PDF Online Free — Add Text & Annotations | PixConvert',
  '/tools/jpg-to-png': 'Convert JPG to PNG Free Online — Lossless | PixConvert',
  '/tools/png-to-jpg': 'Convert PNG to JPG Free Online — Fast & Easy | PixConvert',
  '/tools/webp-to-jpg': 'Convert WebP to JPG Free Online — Instant | PixConvert',
  '/tools/heic-to-jpg': 'Convert HEIC to JPG Free Online — Fast & Easy | PixConvert',
  '/tools/bmp-to-png': 'Convert BMP to PNG Free Online — Lossless | PixConvert',
  '/tools/photo-to-markdown': 'OCR: Convert Photo to Markdown Free Online | PixConvert',
  '/tools/ocr-pdf': 'PDF OCR Free Online — Extract Text from PDF | PixConvert',
  '/tools/sign-pdf': 'Sign PDF Online Free — Add Signature to PDF | PixConvert',
  '/tools/redact-pdf': 'Redact PDF Online Free — Remove Sensitive Text | PixConvert',
  '/tools/compare-pdf': 'Compare PDF Files Free Online — Diff Viewer | PixConvert',
  '/tools/compress-pdf': 'Compress PDF Online Free — Reduce File Size | PixConvert',
  '/analytics': 'Analytics — PixConvert',
};
